### ISSUE TITLE
README content

### ISSUE THREAD

**Issue by Lynnmwova** [Peter-Nyarunda/git-basics#1]
Please provide more details about this repository on your readme file. 
_Regards._

**Comment by Peter-Nyarunda** [comment]
Hi @Lynnmwova ,

Thank you for bringing this up, it is really quite important to have a README to enable others to understand what is going on with the repo.
This repository is dedicated to helping fellow learners of Git, get a broader understanding on Git.
It consists of merely my suggestion and guidelines on learning the Git basics.
You are welcome to assist me create this repository as well as learn and practice a few concepts regarding Git.
Allow me to create a simple draft of the README.md file for a start.

Regards,
Peter Nyarunda.

**Comment by Lynnmwova** [comment]
Looking forward to working with you.

Regards,
Pauline Mwova
